### ISSUE TITLE
TLS not being used on site

### ISSUE THREAD

**Issue by tuxxy** [avatsaev/cloudbleedcheck#1]
Seems kinda funny to not use TLS here, no?

**Comment by avatsaev** [comment]
yeah, but why would anyone need tls on something like this?

**Comment by tuxxy** [comment]
Do you not see the irony?

TLS is free to implement, why would you not do it?

**Comment by avatsaev** [comment]
I will, just wasn't a priority

**Comment by avatsaev** [comment]
certificates installed
