### ISSUE TITLE
Tool check only full domain name

### ISSUE THREAD

**Issue by tonka3000** [avatsaev/cloudbleedcheck#2]
F.e. If I type in **1password** I get a not affected, but if it type in **1password.com** I get an affected message.  
It would be good if we could turn on a contains option (we sometimes leads to more then one result), because sometimes there are multiple domains for the same service.

Greetings
Tonka

**Comment by avatsaev** [comment]
good idea for a new feature, the input clearly demands a domain name, but feel free to implement it and make a PR, I'll test and merge it in.
